param(
    [string]$ClaudeRoot = (Join-Path $PSScriptRoot '..\..\..'),
    [switch]$Check
)

$ClaudeRoot = (Resolve-Path -LiteralPath $ClaudeRoot).Path
$registryPath = Join-Path $ClaudeRoot 'registry.yaml'
$lines = New-Object System.Collections.Generic.List[string]

function Get-RelativePath([string]$FullName) {
    $FullName.Substring($ClaudeRoot.Length).TrimStart('\').Replace('\', '/')
}

function Get-Files([string]$SubPath, [string]$Filter, [switch]$Recurse) {
    $dir = Join-Path $ClaudeRoot $SubPath
    if (-not (Test-Path -LiteralPath $dir)) { return @() }
    @(Get-ChildItem -LiteralPath $dir -Filter $Filter -File -Recurse:$Recurse | Sort-Object FullName)
}

function Add-Section([string]$Name, $Entries) {
    if ($Entries.Count -eq 0) { $lines.Add("${Name}: []"); return }
    $lines.Add("${Name}:")
    foreach ($entry in $Entries) { $lines.Add($entry) }
}

$lines.Add('# Generated by sync-registry.ps1 -- do not edit by hand.')
$lines.Add('version: 1')
$lines.Add('instructions: ../CLAUDE.md')
$lines.Add('readme: ../README.md')

$agents = @(Get-Files 'agents' '*.md' | ForEach-Object {
    "  - id: $($_.BaseName)`n    definition: $(Get-RelativePath $_.FullName)"
})
Add-Section 'agents' $agents

$skills = @(Get-Files 'skills' 'SKILL.md' -Recurse | ForEach-Object {
    "  - id: $($_.Directory.Name)`n    definition: $(Get-RelativePath $_.FullName)"
})
Add-Section 'skills' $skills

$knowledge = @(Get-Files 'knowledge' '*.md' -Recurse | ForEach-Object { "  - $(Get-RelativePath $_.FullName)" })
Add-Section 'knowledge' $knowledge

$playbooks = @(Get-Files 'playbooks' '*.md' | Where-Object { $_.Name -ne 'README.md' } | ForEach-Object {
    "  - id: $($_.BaseName)`n    definition: $(Get-RelativePath $_.FullName)"
})
Add-Section 'playbooks' $playbooks

$templatesDir = Join-Path $ClaudeRoot 'templates'
$templates = @()
if (Test-Path -LiteralPath $templatesDir) {
    $templates = @(Get-ChildItem -LiteralPath $templatesDir -Directory | Sort-Object Name | ForEach-Object {
        "  - id: $($_.Name)`n    root: $(Get-RelativePath $_.FullName)/"
    })
}
Add-Section 'templates' $templates

# A tool's lifecycle comes from its own manifest, so the index cannot disagree with it.
$official = New-Object System.Collections.Generic.List[string]
$candidate = New-Object System.Collections.Generic.List[string]
foreach ($manifest in Get-Files 'tools' 'tool.yaml' -Recurse) {
    $content = Get-Content -LiteralPath $manifest.FullName -Raw
    $id = $manifest.Directory.Name
    if ($content -match '(?m)^id:\s*(.+?)\s*$') { $id = $Matches[1] }
    $lifecycle = 'candidate'
    if ($content -match '(?m)^lifecycle:\s*(.+?)\s*$') { $lifecycle = $Matches[1] }

    $entry = "    - id: $id`n      manifest: $(Get-RelativePath $manifest.FullName)"
    if ($lifecycle -eq 'official') { $official.Add($entry) } else { $candidate.Add($entry) }
}

$lines.Add('tools:')
foreach ($group in @(@{ Name = 'official'; Entries = $official }, @{ Name = 'candidate'; Entries = $candidate })) {
    if ($group.Entries.Count -eq 0) {
        $lines.Add("  $($group.Name): []")
    }
    else {
        $lines.Add("  $($group.Name):")
        foreach ($entry in $group.Entries) { $lines.Add($entry) }
    }
}

$text = ($lines -join "`n") + "`n"

if ($Check) {
    $current = ''
    if (Test-Path -LiteralPath $registryPath) { $current = [System.IO.File]::ReadAllText($registryPath) }
    if ($current.Replace("`r`n", "`n") -ne $text) {
        Write-Error "registry.yaml is out of date. Run sync-registry.ps1 to regenerate it."
        exit 1
    }
    Write-Output 'registry.yaml is up to date.'
    exit 0
}

[System.IO.File]::WriteAllText($registryPath, $text, (New-Object System.Text.UTF8Encoding($false)))
Write-Output "Wrote registry.yaml ($($agents.Count) agents, $($skills.Count) skills, $($playbooks.Count) playbooks, $($official.Count + $candidate.Count) tools)."
